# ######## Window rules ########
windowrule = center 1, match:float true, match:xwayland 0  # Center all floating windows (not xwayland cause popups)

# Float
windowrule = float true, match:class guifetch  # FlafyDev/guifetch
windowrule = float true, match:class yad
windowrule = float true, match:class zenity
windowrule = float true, match:class wev
windowrule = float true, match:class blueman-manager
windowrule = float true, match:class nm-connection-editor
windowrule = float true, match:class feh
windowrule = float true, match:class imv
windowrule = float true, match:class org\.quickshell

# Float, resize and center
windowrule = float true, match:class org\.gnome\.Settings
windowrule = size 70% 80%, match:class org\.gnome\.Settings
windowrule = center 1, match:class org\.gnome\.Settings
windowrule = float true, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = size 60% 70%, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = center 1, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = float true, match:class nwg-look
windowrule = size 50% 60%, match:class nwg-look
windowrule = center 1, match:class nwg-look

# Special workspaces
windowrule = workspace special:btop, match:title btop
windowrule = workspace special:music, match:class Spotify

# Dialogs
windowrule = float true, match:title (Select|Open)( a)? (File|Folder)(s)?
windowrule = float true, match:title File (Operation|Upload)( Progress)?
windowrule = float true, match:title .* Properties
windowrule = float true, match:title Export Image as PNG
windowrule = float true, match:title GIMP Crash Debug
windowrule = float true, match:title Save As
windowrule = float true, match:title Library

# Steam
windowrule = match:class steam
windowrule = float true, match:class ^(steam)$, match:title negative:^(Steam)$
windowrule = immediate true, match:class steam_app_[0-9]+  # Allow tearing for steam games
windowrule = idle_inhibit always, match:class steam_app_[0-9]+  # Always idle inhibit when playing a steam game

# Custom Rules
windowrule = monitor 1, match:class vesktop
windowrule = workspace special:music, match:class spotify
windowrule = float true, match:class (paradox-launcher-v2)
windowrule = float true, match:class (RimSort)
windowrule = float true, match:class (forzarichpresence)