general {
    # Gaps and border
    gaps_in = 4
    gaps_out = 5
    gaps_workspaces = 50
    
    border_size = 1
    resize_on_border = true

    no_focus_fallback = true
    
    allow_tearing = true # This just allows the `immediate` window rule to work
    
    snap {
    	enabled = true
    }
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
    # precise_mouse_move = true
}

debug {
    disable_logs = false
}

cursor {
    no_hardware_cursors = 1
}